/**
 * Copyright IBM Corp. 2021, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'file', { get: function () { return require('./file'); } });
Object.defineProperty(exports, 'dataArchiveFile', { get: function () { return require('./data-archive-file'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

